In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import regex

In [3]:
df_amazon_products = pd.read_csv('datasets/products.csv')
#df_amazon_sales = pd.read_csv('datasets/Amazon_Sales_Dataset.csv')
df_amazon_beauty = pd.read_csv('datasets/Amazon_Beauty_Recommendation.csv')

In [4]:
df_amazon_products = df_amazon_products.set_index('asin')
df_amazon_products.head()

,title,description,price,images,features,rating
asin,,,,,,
B001FB5IMI,NIVEA Soft Moisturizing Creme 6.8 Ounce (Pack ...,NaN,26.99,[{'thumb': 'https://m.media-amazon.com/images/...,"['Light and creamy formula', 'Enriched with Vi...",4.7
B001EHF954,Farouk PM7426 Chi Mini Flat Iron and Mini Pro ...,NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Chi mini flat iron features 1 1/4 inch ceram...,3.4
B000NWDSAE,"Neutrogena Oil-Free Acne Face Scrub, 2% Salicy...",NaN,6.78,[{'thumb': 'https://m.media-amazon.com/images/...,['4.2-fluid ounce tube of Neutrogena Oil-Free ...,4.6
B00BEGEQKE,Sleek Makeup - Blush By 3 Palette (367- Lace),As one of the fastest growing brands on the hi...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Blush by 3 is the ultimate palette offering ...,3.7
B008IH8SUQ,"Best Choice Products Silver 19"" Lockable Alumi...",NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"['High quality aluminum frame', 'Mirror', 'Rem...",4.1

In [5]:
#df_amazon_beauty = df_amazon_beauty.set_index('asin')
df_amazon_beauty.head()

,UserId,ProductId,ProductType,Rating,Timestamp,URL
0,A3NHUQ33CFH3VM,B00LLPT4HI,Eyeliner & Kajal,5,1405814400,https://www.amazon.in/Maybelline-Colossal-Kaja...
1,A1TIRNQ7O4REOH,B00LLPT4HI,Eyeliner & Kajal,4,1405987200,https://www.amazon.in/Maybelline-Colossal-Kaja...
2,A2Y36BR4YSY9F7,B00LLPT4HI,Eyeliner & Kajal,5,1405728000,https://www.amazon.in/Maybelline-Colossal-Kaja...
3,A23H6FAOLEMAKC,B00LLPT4HI,Eyeliner & Kajal,5,1405814400,https://www.amazon.in/Maybelline-Colossal-Kaja...
4,A3CHYZGF3OO6WD,B00LLPT4HI,Eyeliner & Kajal,5,1405641600,https://www.amazon.in/Maybelline-Colossal-Kaja...

In [7]:
pd.concat([df_amazon_products, pd.DataFrame.from_dict([{'asin': 'XXX', 'title': pd.NA}]).set_index('asin')]).tail(5)

,title,description,price,images,features,rating
asin,,,,,,
B00H4I5I12,"Impress, Anti-Aging Facial Pad Program, 1 Box",NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Get the skin you deserve: Our specially form...,4.0
B002ES6Z0K,Sun'n'Fun Broad Spectrum UVA+UVB,NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],4.0
B003Y04OK0,Sweetsation Therapy / YUNASENCE ILIGHT Organic...,NaN,26.0,[{'thumb': 'https://m.media-amazon.com/images/...,['After 4 weeks it visibly reduces fine lines ...,4.2
B000HVW96A,Under EyeBryten Severe Dark Circles and Under-...,NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Helps diminish severe dark circles and under...,3.5
XXX,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
text = 'https://www.amazon.in/Dettol-Body-Wash-shower-Refresh/dp/B07XTSQT4R/ref=sr_1_37?crid=3NKGP4OZB9248&keywords=body+wash&pf_rd_i=1374276031&pf_rd_m=A1VBAL9TL5WCBF&pf_rd_p=218f8944-f0f6-41af-ad51-958d2a04fb2f&pf_rd_r=Q92BV6MWDP2BAZXH1E9P&pf_rd_s=merchandised-search-4&qid=1680067965&s=beauty&sprefix=body+%2Cbeauty%2C193&sr=1-37'
r = regex.Regex(r'https://www\.amazon\.in/(.*)/dp/')
def extract_name(text):
    matchs = r.findall(text)
    if len(matchs) > 0:
        return matchs[0].replace('-', ' ')
    else:
        return np.NAN
extract_name(text)

'Dettol Body Wash shower Refresh'

In [8]:
df_amazon_beauty_mod = df_amazon_beauty.groupby(by= 'ProductId').min()[['URL']]
df_amazon_beauty_mod['name'] = df_amazon_beauty_mod['URL'].apply(extract_name)
df_amazon_beauty_mod.index.set_names('asin', inplace=True)
df_amazon_beauty_mod.rename(columns={'name':'title'}, inplace=True)
df_amazon_beauty_mod.head()

,URL,title
asin,,
B0000020TR,https://www.amazon.in/Lakme-Absolute-Stylist-C...,Lakme Absolute Stylist Color Scarlet
B00000JGVX,https://www.amazon.in/Revson-Glossy-Coverage-R...,Revson Glossy Coverage Resistant Lasting
B000024M5R,https://www.amazon.in/NAMONAVKAR-Lasting-Metal...,NAMONAVKAR Lasting Metallic Polish Enamel
B00004TMFE,https://www.amazon.in/JUICE-Glitter-Resistant-...,JUICE Glitter Resistant pigmented Intense
B00004TUBL,https://www.amazon.in/Revlon-Summer-Matte-Ness...,Revlon Summer Matte Ness Nail Enamel

In [10]:
A = set(df_amazon_products.index)
B = set(df_amazon_beauty_mod.index)
C = B.difference(A)
len(A), len(B), len(C)

(11875, 23838, 11963)

In [11]:
df_all_products = pd.concat([df_amazon_products, df_amazon_beauty_mod[['title']].loc[list(C)]])
df_all_products.head()

,title,description,price,images,features,rating
asin,,,,,,
B001FB5IMI,NIVEA Soft Moisturizing Creme 6.8 Ounce (Pack ...,NaN,26.99,[{'thumb': 'https://m.media-amazon.com/images/...,"['Light and creamy formula', 'Enriched with Vi...",4.7
B001EHF954,Farouk PM7426 Chi Mini Flat Iron and Mini Pro ...,NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Chi mini flat iron features 1 1/4 inch ceram...,3.4
B000NWDSAE,"Neutrogena Oil-Free Acne Face Scrub, 2% Salicy...",NaN,6.78,[{'thumb': 'https://m.media-amazon.com/images/...,['4.2-fluid ounce tube of Neutrogena Oil-Free ...,4.6
B00BEGEQKE,Sleek Makeup - Blush By 3 Palette (367- Lace),As one of the fastest growing brands on the hi...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,['Blush by 3 is the ultimate palette offering ...,3.7
B008IH8SUQ,"Best Choice Products Silver 19"" Lockable Alumi...",NaN,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"['High quality aluminum frame', 'Mirror', 'Rem...",4.1

In [12]:
print(f'Total de datos: {df_all_products.shape[0]}\n')
print(f'Por ciento de datos faltantes:\n{np.round(100 - df_all_products.count() / df_all_products.shape[0] * 100, 2)}')

Total de datos: 23838

Por ciento de datos faltantes:
title           9.35
description    95.19
price          84.06
images         50.18
features       50.18
rating         50.95
dtype: float64

In [126]:
df_all_products.to_csv('datasets/all_products.csv')

In [13]:
df_amazon_beauty.groupby(by='UserId')

In [14]:
df_sales = df_amazon_beauty.sort_values(by=['UserId', 'Timestamp'], ascending=[True,True])#.set_index(['UserId', 'Timestamp'])
df_sales.head()

,UserId,ProductId,ProductType,Rating,Timestamp,URL
1114383,A000186437REL8X2RW8UW,B000JD4N9M,Nail Polish,5,1397088000,https://www.amazon.in/Revlon-Nail-Enamel-Red-F...
118470,A0002574WYJMBWKNCPY8,B00AH4TJNS,Cream & Moisturizer,3,1391558400,https://www.amazon.in/Mamaearth-Oil-Free-Moist...
258618,A00029263J863WSR0TDRS,B00766SGE8,Body Lotion,5,1402876800,https://www.amazon.in/VLCC-White-Moisturising-...
701149,A00031961JI1CBNV98TW,B002OO16QC,Face Wash & Cleansers,5,1395532800,https://www.amazon.in/Nivea-Dark-Spot-Reductio...
266864,A000325234LCBTFVL1QK4,B006ZN1B1S,Face Serum,5,1358208000,https://www.amazon.in/Loreal-LOreal-Paris-Glyc...

In [15]:
df_merge = df_sales[['UserId','Timestamp','ProductId']].merge(df_all_products[['title']], left_on='ProductId', right_on='asin')
df_merge.head()

,UserId,Timestamp,ProductId,title
0,A000186437REL8X2RW8UW,1397088000,B000JD4N9M,Revlon Nail Enamel Red Fiesta
1,A101L6NFAWSKCN,1394150400,B000JD4N9M,Revlon Nail Enamel Red Fiesta
2,A10W2W29KT4YZ2,1380672000,B000JD4N9M,Revlon Nail Enamel Red Fiesta
3,A11CUQ2V3KVL39,1381363200,B000JD4N9M,Revlon Nail Enamel Red Fiesta
4,A11ZCF4B04FPLE,1377561600,B000JD4N9M,Revlon Nail Enamel Red Fiesta

In [16]:
view = df_merge.groupby(by='UserId').count()
view = view[(view['Timestamp'] == view['title']) & (view['Timestamp'] > 1)]#.reset_index()
df_sales_merge = df_sales[df_sales['UserId'].isin(view.index)][['UserId','Timestamp','ProductId']]
df_sales_merge.head()

                       UserId   Timestamp   ProductId
447493   A0010876CNE3ILIM9HV0  1367884800  B004MKEMPI
356781   A0010876CNE3ILIM9HV0  1372809600  B005HKST1U
812260   A0010876CNE3ILIM9HV0  1386547200  B001KYRVSO
386332   A0010876CNE3ILIM9HV0  1390521600  B0055MYJ0U
263557  A00262022JQPXX5SXEVJR  1397520000  B0071H61FS

In [205]:
df_sequences = pd.DataFrame(df_sales_merge.groupby(by='UserId').apply(lambda x: list(x['ProductId'])), columns=['Sequences'])
df_sequences.head()

                                                              Sequences
UserId
A0010876CNE3ILIM9HV0   [B004MKEMPI, B005HKST1U, B001KYRVSO, B0055MYJ0U]
A00262022JQPXX5SXEVJR  [B0071H61FS, B005FYJB92, B003NEZ0R8, B000NJE14E]
A00338282E99B8OR2JYTZ              [B00AO6UKQO, B00B0RTA30, B00BM4GG9C]
A004205218STRNUW6PPPA                          [B005UG1YS6, B0002Z0R9C]
A00442102RVQB9UWAU5KD                          [B0056AJGU4, B00597GJAO]

In [25]:
df_sequences['Length'].sum()

(151640,)

In [207]:
df_sequences['Length'] = df_sequences['Sequences'].apply(len)
df_sequences

,Sequences,Length
UserId,,
A0010876CNE3ILIM9HV0,"[B004MKEMPI, B005HKST1U, B001KYRVSO, B0055MYJ0U]",4
A00262022JQPXX5SXEVJR,"[B0071H61FS, B005FYJB92, B003NEZ0R8, B000NJE14E]",4
A00338282E99B8OR2JYTZ,"[B00AO6UKQO, B00B0RTA30, B00BM4GG9C]",3
A004205218STRNUW6PPPA,"[B005UG1YS6, B0002Z0R9C]",2
A00442102RVQB9UWAU5KD,"[B0056AJGU4, B00597GJAO]",2
...,...,...
AZZUZWE3JL9QT,"[B007TQBGCY, B00B594NEY]",2
AZZV9PDNMCOZW,"[B000I20Q72, B003AXEGWW, B003AXAN3I]",3
AZZVZL4QEHEHO,"[B00188IFHS, B0017ZNPEU]",2
AZZWJ3LICUEKJ,"[B0034F9K36, B001JQLNJ6, B000QUM5LG, B0001KO7PI]",4
AZZYW4YOE1B6E,"[B001410OG4, B001E96MZ8, B000NWDSAE]",3

In [230]:
df_sequences.to_csv('datasets/sequences.csv')